# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  test:
    strategy:
      fail-fast: false
      matrix:
        spec:
          - org.osgi.test.cases.async.secure
          - org.osgi.test.cases.async
          - org.osgi.test.cases.bundle.annotations
          - org.osgi.test.cases.cdi.secure
          - org.osgi.test.cases.cdi
          - org.osgi.test.cases.clusterinfo.secure
          - org.osgi.test.cases.clusterinfo
          - org.osgi.test.cases.cm
          - org.osgi.test.cases.component.annotations
          - org.osgi.test.cases.component
          - org.osgi.test.cases.condpermadmin
          - org.osgi.test.cases.configurator.secure
          - org.osgi.test.cases.configurator
          - org.osgi.test.cases.converter
          - org.osgi.test.cases.coordinator.secure
          - org.osgi.test.cases.coordinator
          - org.osgi.test.cases.dal.functions
          - org.osgi.test.cases.dal.secure
          - org.osgi.test.cases.dal
          - org.osgi.test.cases.device
          - org.osgi.test.cases.dmt.tc1
          - org.osgi.test.cases.dmt.tc2
          - org.osgi.test.cases.dmt.tc3
          - org.osgi.test.cases.dmt.tc4
          - org.osgi.test.cases.enocean
          - org.osgi.test.cases.event.secure
          - org.osgi.test.cases.event
          - org.osgi.test.cases.framework.launch.secure
          - org.osgi.test.cases.framework.launch
          - org.osgi.test.cases.framework.secure
          - org.osgi.test.cases.framework
          - org.osgi.test.cases.http.whiteboard.secure
          - org.osgi.test.cases.http.whiteboard
          - org.osgi.test.cases.http
          - org.osgi.test.cases.jaxrs
          - org.osgi.test.cases.jdbc
          - org.osgi.test.cases.jndi.secure
          - org.osgi.test.cases.jndi
          - org.osgi.test.cases.jpa
          - org.osgi.test.cases.log.launch
          - org.osgi.test.cases.log.stream
          - org.osgi.test.cases.log
          - org.osgi.test.cases.metatype.annotations
          - org.osgi.test.cases.metatype
          - org.osgi.test.cases.networkadapter
          - org.osgi.test.cases.onem2m
          - org.osgi.test.cases.permissionadmin
          - org.osgi.test.cases.prefs
          - org.osgi.test.cases.promise
          - org.osgi.test.cases.pushstream
          - org.osgi.test.cases.remoteserviceadmin.secure
          - org.osgi.test.cases.remoteserviceadmin
          - org.osgi.test.cases.remoteservices
          - org.osgi.test.cases.repository
          - org.osgi.test.cases.residentialmanagement
          - org.osgi.test.cases.resolver
          - org.osgi.test.cases.resourcemonitoring
          - org.osgi.test.cases.rest.client.js
          - org.osgi.test.cases.rest.client
          - org.osgi.test.cases.rest
          - org.osgi.test.cases.serial
          - org.osgi.test.cases.serviceloader.secure
          - org.osgi.test.cases.serviceloader
          - org.osgi.test.cases.tr069todmt
          - org.osgi.test.cases.tracker
          - org.osgi.test.cases.transaction.control.jdbc
          - org.osgi.test.cases.transaction.control.jpa
          - org.osgi.test.cases.transaction.control
          - org.osgi.test.cases.transaction
          - org.osgi.test.cases.upnp
          - org.osgi.test.cases.url
          - org.osgi.test.cases.usbinfo
          - org.osgi.test.cases.useradmin
          - org.osgi.test.cases.webcontainer
          - org.osgi.test.cases.wireadmin
          - org.osgi.test.cases.xml
          - org.osgi.test.cases.zigbee 
        java: [ 8,11 ]
        os: [ linux,windows ]
    name: TCK ${{ matrix.spec }} with ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Run TCK
      run: |
        echo  ${{ matrix.spec }} ${{ matrix.java }} ${{ matrix.os }}
