# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  test:
    strategy:
      fail-fast: false
      matrix:
        spec:
          - ds
          - converter
          - framework
          - event
        java: [ 8,11 ]
        os: [ linux,windows ]
    name: TCK ${{ matrix.spec }} with ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Run TCK
      run: |
        echo  ${{ matrix.spec }} ${{ matrix.java }} ${{ matrix.os }}
